//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rental_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public int AdId { get; set; }
        public int UserId { get; set; }
        public int SpecId { get; set; }
        public int AddressId { get; set; }
        public int Satus { get; set; }
        public int Availability { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Specification Specification { get; set; }
        public virtual User User { get; set; }
    }
}
